void set_angle(double r);
void set_pos(int x, int y);
void set_dpos(double x, double y);
void dforward(double len, GC gc);
void dturn(double r);
void turn(int r);
double get_posx();
double get_posy();
double get_angle();
void up();
void down();
